pub const TEAMS: [&str; 196] = [
    "Les Monstres de Marshmallow",
    "Les Télégraphistes de la Galaxie",
    "Les Centaures Turbulents",
    "Les Slalomeurs de la Fantaisie",
    "Les Lutins Affamés",
    "Les Étrangers Flamboyants",
    "Les Cosaques de l’Ouest",
    "Les Épéistes du Royaume",
    "Les Patineurs de la Révolution",
    "Les Gladiateurs du Temps",
    "Les Grenouilles de l’Écume",
    "Les Vagabonds de l’Espace",
    "Les Cœurs Héroïques",
    "Les Bandits de l’Aurore",
    "Les Mousquetaires des Ténèbres",
    "Les Éclaireurs de l’Avenir",
    "Les Chevaliers de l’Hiver",
    "Les Fous Volants de la Nuit",
    "Les Sorciers de l’Orient",
    "Les Hiérarques de la Paix",
    "Les Cavaliers du Vent",
    "Les Cavaliers du Destin",
    "Les Coyotes de la Colère",
    "Les Cowboys de la Vague",
    "Les Dragons de l’Avenir",
    "Les Faucons des Cieux",
    "Les Rapaces de l’Orange",
    "Les Léopards de la Forêt",
    "Les Écureuils des Montagnes",
    "Les Tigres de la Nuit",
    "Les Loups du Vent",
    "Les Alligators du Marais",
    "Les Lézards de la Pluie",
    "Les Éléphants de la Savane",
    "Les Pumas du Seigneur",
    "Les Grenouilles du Soir",
    "Les Diables de la Mer",
    "Les Cocodrilles des Marées",
    "Les Écureuils de la Cascade",
    "Les Lions des Champs",
    "Les Ours des Sables",
    "Les Requins des Profondeurs",
    "Les Aigles des Cimes",
    "Les Flamants Chill",
    "Les Vengeurs Divins",
    "Les Rockstars du Match",
    "Les Sirènes Invincibles",
    "Les Chefs de la Victoire",
    "Les Éclaireurs de l’Impossible",
    "Les As de La Finale",
    "Les Nageurs de la Victoire",
    "Les Anciens Combattants",
    "Les Lions de La Gloire",
    "Les Renegades Intrépides",
    "Les Braves des Terres Sauvages",
    "Les Faucons des Étoiles",
    "Les Fils de la Légende",
    "Les Cavaliers de la Vitesse",
    "Les Chevaliers de la Force",
    "Les Ecuyers des Ténèbres",
    "Les Destroyers du Défi",
    "Les Fléchettes de la Bravoure",
    "Les Cavaliers de la Fortune",
    "Les Filles de l’Avenir",
    "Les Gladiateurs du Feu",
    "Les Étoiles du Destin",
    "Les Gourmands",
    "Les Infatigables",
    "Les Terminateurs",
    "Les Cheveux Bouclés",
    "Les Indestructibles",
    "Les Chats Sauvages",
    "Les Fantômes Des Jeux",
    "Les Étoiles D’or",
    "Les Rapides",
    "Les Saboteurs",
    "Les Agents Secrets",
    "Les Démons de la Nuit",
    "Les Lutteurs",
    "Les Pieds Fous",
    "Les Éponges",
    "Les Aventuriers",
    "Les Loups Féroces",
    "Les Éclaireurs",
    "Les Équilibristes",
    "Les Dragons",
    "Les Éternels",
    "Les énigmes de Sherlock",
    "Les aventuriers du temps",
    "Les cerveaux explosifs",
    "Les Sherlockholmes",
    "Les crackers de code",
    "Les génies de l’évasion",
    "Les penseurs de l’impossible",
    "Les aventuriers des mondes virtuels",
    "Les experts de la déduction",
    "Les déchiffreurs de l’énigme",
    "Les trouveurs d’indices",
    "Les démineurs de l’évasion",
    "Les explorateurs de la résolution",
    "Les seigneurs de la déduction",
    "Les idées créatives",
    "Les spécialistes de l’énigme",
    "Les décodeurs du labyrinthe",
    "Les aventuriers du mystère",
    "Les résolveurs de l’énigme",
    "La Boule de Feu",
    "Les Boulistes de la Colline",
    "L’Île des Pétanqueurs",
    "Les Dragons de la Pétanque",
    "Les Boulistes du Dimanche",
    "Les Défenseurs de la Pétanque",
    "Les Petits Poussins de la Pétanque",
    "Les Équilibristes de la Pétanque",
    "Les Cavaliers de la Pétanque",
    "Les Messagers de la Pétanque",
    "Les Aventuriers de la Pétanque",
    "Les Éclairés de la Pétanque",
    "Les Joyeux Boulistes",
    "Les Géants de la Pétanque",
    "La Garde de la Pétanque",
    "Les Célébrants de la Pétanque",
    "Les Rêveurs de la Pétanque",
    "Les Gladiateurs de la Pétanque",
    "Les Champions de la Pétanque",
    "Les Artistes de la Pétanque",
    "Les Vagabonds de la Pétanque",
    "Les Poulbots de la Pétanque",
    "Les Bérets Rouges de la Pétanque",
    "Les Boulistes du Sud",
    "Les Amoureux de la Pétanque",
    "Les Éternels de la Pétanque",
    "Les Héros de la Pétanque",
    "Les Romantiques de la Pétanque",
    "Les Maîtres de la Pétanque",
    "Les Fondues de Badminton",
    "Les Fous Volants",
    "Les Oiseaux de Nuit",
    "Les Faucons à Plumes",
    "Les Enfants de la Chance",
    "Les Bâtonnets du Sucre",
    "Les Ailes du Destin",
    "Les Rois des Raquettes",
    "Les Fous de Vol",
    "Les Éclaireurs de But",
    "Les Lancers Rapides",
    "Les Flèches du Hasard",
    "Les Chronomètres des Raquettes",
    "Les Éperviers des Volants",
    "Les Sauteurs de Haut Vol",
    "Les Filets de la Fortune",
    "Les Foudres de Volants",
    "Les Équilibristes de la Plume",
    "Les Plumes des Vainqueurs",
    "Les Flèches Foudroyantes",
    "Les Aigles du Filet",
    "Les Éclaircisseurs des Ailes",
    "Les Fous de la Plume",
    "Les Équilibristes de Volants",
    "Les Oiseaux de Raquettes",
    "Les Flèches des Fous",
    "Les Lames de Force",
    "Les Filets de la Destinée",
    "Les Foudres de Buts",
    "Les Raquettes des Étoiles",
    "Les Coups de Foudre",
    "Les Bons à Rien",
    "Les Beaux et les Méchants",
    "Les Bons et les Laids",
    "Les Cerveaux et les Biceps",
    "Les Boiteux et les Baveux",
    "Les Vrais et les Faux",
    "Les Pas Prêts et les Prêts",
    "Les Follement Fous",
    "Les Grands et les Petits",
    "Les Bien et les Mal Blonds",
    "Les Bons et les Mauvais Garçons",
    "Les Tireurs et les Dribbleurs",
    "Les Râleurs et les Pleureurs",
    "Les Vrais et les Faux Durables",
    "Les Fous et les Sages",
    "Les Durs et les Doux",
    "Les Amateurs et les Professionnels",
    "Les As et les Nuls",
    "Les Rapides et les Lents",
    "Les Fortes et les Faibles Têtes",
    "Les Fêtards et les Calmes",
    "Les Colleurs et les Copieurs",
    "Les Robustes et les Fragiles",
    "Les Heureux et les Malheureux",
    "Les Succès et les Échecs",
    "Les Cool et les Ringards",
    "Les Gros et les Petits Volontaires",
    "Les Parfaits et les Imparfaits",
    "Les Bons et les Mauvais Joueurs",
    "Les Romantiques et les Insensibles",
];
